### ISSUE TITLE
Kills not being tracked/updated real time

### ISSUE THREAD

**Issue by Wolfang42** [WarmedxMints/ODMissionStacker#14] opened 2022-11-12 15:08 UTC

**Comment by postscripter8** [comment] 2023-01-10 16:58
I believe this is caused by the game mixing horizons and odyssey events after the mission pools were joint in *Live mode*.
This tool needs the same change as the trade mission stacker [here](https://github.com/WarmedxMints/OD-Trade-Misson-Tracker/commit/9d1b735fb9c553b395228fced12cd34c579562b1).

**Comment by Lusiphur** [comment] 2023-01-20 10:09
Was just coming here to raise this issue. Just started using this tool yesterday and it's definitely not updating automatically for me. This is using the latest release 1.7.1.

**Comment by danielwow12** [comment] 2023-02-02 14:34
I am having this issue as well. The program was working perfect for me before the recent patch. It appears to be getting confused between horizons/odyssey.

**Comment by WarmedxMints** [comment] 2023-02-09 14:10
Should be sorted now hopefully.  The game has a habit of reporting bools in the events as false when they should be true.  However, the two modes have now been merged.

https://github.com/WarmedxMints/ODMissionStacker/releases/tag/v1.7.2

**Closed as completed by WarmedxMints** 2023-02-09 14:10 UTC
